baseURL = "https://docs.space-cloud.io/"
languageCode = "en-us"
title = "Space Cloud"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML","RSS","Algolia"]

[outputFormats.Algolia]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
  notAlternative = true
