[build]
  publish = "public"
  command = "sh scripts/build.sh"
[context.production.environment]
  HUGO_VERSION = "0.64.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.64.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.64.0"  

[[redirects]]
  from = "/getting-started/*"
  to = "https://learn.spaceuptech.com/space-cloud/basics/setup/"
  status = 301
  force = true